-- DROP THE DATABASE IF EXISTS
DROP DATABASE IF EXISTS employeeTracker;
-- CREATE DATABASE
CREATE DATABASE employeeTracker;

USE employeeTracker;

-- CREATE EMPLOYEE TABLE
CREATE TABLE employeeTable (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    role_id INTEGER, 
    manager_id INTEGER
);

CREATE TABLE roleTable (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(30) NOT NULL, 
    salary DECIMAL NOT NULL,
    department_id INTEGER
);

-- CREATE DEPARTMENT TABLE
CREATE TABLE departmentTable (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

