-- DROP THE DATABASE IF EXISTS
DROP DATABASE IF EXISTS employeeTracker;
-- CREATE DATABASE
CREATE DATABASE employeeTracker;

USE employeeTracker;

-- CREATE EMPLOYEE TABLE
CREATE TABLE employeeTable (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    role_id INT,
    manager_id INT,
    FOREIGN KEY(manager_id)
    REFERENCES employeeTable(id)
);

-- CREATE ROLE TABLE
CREATE TABLE roleTable (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    salary DECIMAL NOT NULL,
    department_id INT
);

-- CREATE DEPARTMENT TABLE
CREATE TABLE departmentTable (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
